### ISSUE TITLE
fix echelon binary

### ISSUE THREAD

**Issue by boblannon** [influence-usa/scrapers-us-federal#5]
here's the error. do i need to have the source files locally?

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at echelon.simple$loading__4958__auto__.invoke(simple.clj:1)
        at echelon.simple__init.load(Unknown Source)
        at echelon.simple__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at echelon.simple.<clinit>(Unknown Source)
Caused by: java.io.FileNotFoundException: src/echelon/parser.bnf (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at clojure.java.io$fn__8702.invoke(io.clj:229)
        at clojure.java.io$fn__8615$G__8606__8622.invoke(io.clj:69)
        at clojure.java.io$fn__8714.invoke(io.clj:258)
        at clojure.java.io$fn__8615$G__8606__8622.invoke(io.clj:69)
        at clojure.java.io$fn__8676.invoke(io.clj:165)
        at clojure.java.io$fn__8628$G__8610__8635.invoke(io.clj:69)
        at clojure.java.io$reader.doInvoke(io.clj:102)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$slurp.doInvoke(core.clj:6390)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at echelon.text__init.load(Unknown Source)
        at echelon.text__init.<clinit>(Unknown Source)
        ... 31 more
```

**Comment by zmaril** [comment]
This should be fixed now in the new jar that I'm about to send you.
